version: "3.9"

services:
  api_server:
    build:
      context: .
      dockerfile: "Dockerfile"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    container_name: api_server
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"